title: Prabin Deka
url:   http://www.prabindeka.com
author: 
  name:    
  email:   pdeka@thoughtworks.com
  open_id:
    - http://enkiblog.com
    - http://secondaryopenid.com

# Delete the following section if your site will not be acting as an OpenID delegate
#open_id_delegation:
#  server:   http://www.myopenid.com/server
#  delegate: http://username.myopenid.com
